#!/usr/bin/env python
"""Formal verification of the external validation design, before campaign launch.

The surrogate reliability gate is only meaningful if its external set is genuinely
external and genuinely capable of testing the surface. Seven conditions, each
checked by computation rather than by reading, and each failing loudly.

  1. no external run appears in the fitting design;
  2. fitting and validation fractions have opposite defining relation;
  3. the complementary fraction has the same factorial resolution;
  4. every configuration is feasible under the declared bounds and types;
  5. the axial runs are distinct from both factorial fractions;
  6. the external set can identify the terms of the fitted response surface;
  7. no validation response can reach any fitting stage.

Condition 7 is a property of the code rather than of the point set, so it is
checked by static inspection of the pipeline's call graph and by a runtime tripwire
the campaign runner installs.

Writes audits/external_validation_verification.json and exits non-zero on any
failure.

Usage:  python verify_external_validation_design.py
"""
from __future__ import annotations

import ast
import importlib.util
import itertools
import json
import sys
from pathlib import Path

import numpy as np
import pandas as pd

REPO = Path(__file__).resolve().parents[3]
HERE = Path(__file__).resolve().parent
OUT = REPO / "papers" / "xgboost_hpo_vrfnbi" / "audits"
DESIGN = REPO / "data" / "design" / "hyperparameter_design.csv"

spec = importlib.util.spec_from_file_location(
    "pilot_stage_a", HERE / "pilot_stage_a_screening.py")
pilot = importlib.util.module_from_spec(spec)
spec.loader.exec_module(pilot)
PARAMS, BOUNDS, INTS = pilot.PARAMS, pilot.BOUNDS, pilot.INTS


def coded(df: pd.DataFrame) -> np.ndarray:
    lo = np.array([BOUNDS[p][0] for p in PARAMS])
    hi = np.array([BOUNDS[p][1] for p in PARAMS])
    return 2 * (df[PARAMS].to_numpy(dtype=float) - lo) / (hi - lo) - 1


def load_design() -> pd.DataFrame:
    d = pd.read_csv(DESIGN, sep=";", decimal=",", encoding="utf-8-sig")
    d.columns = [str(c).strip().strip('"') for c in d.columns]
    return d


def defining_relation(corners: np.ndarray) -> set[float]:
    """Sign of the seven-factor product on each corner run.

    A half fraction of 2^7 generated by I = ABCDEFG has a constant product; the
    complementary fraction has the opposite constant.
    """
    return set(np.round(np.sign(corners).prod(axis=1), 9).tolist())


def resolution(corners: np.ndarray) -> int:
    """Resolution of a two-level fraction: the length of its shortest word.

    Checked directly: the fraction has resolution R when every effect of order
    below R is estimable, that is when no product of fewer than R columns is
    constant across the runs.
    """
    k = corners.shape[1]
    for order in range(1, k + 1):
        for combo in itertools.combinations(range(k), order):
            prod = np.sign(corners[:, list(combo)]).prod(axis=1)
            if len(set(np.round(prod, 9).tolist())) == 1:
                return order          # shortest word found
    return k + 1


def rsm_terms(k: int):
    out = [()] + [(i,) for i in range(k)] + [(i, i) for i in range(k)]
    out += [(i, j) for i in range(k) for j in range(i + 1, k)]
    return out


def basis(Xc: np.ndarray, terms) -> np.ndarray:
    cols = []
    for tm in terms:
        v = np.ones(len(Xc))
        for i in tm:
            v = v * Xc[:, i]
        cols.append(v)
    return np.column_stack(cols)


def check_no_validation_leak(module_path: Path) -> dict:
    """Static check: which stages receive the validation frame as an argument.

    Any call that passes the validation frame into a fitting routine is a leak.
    The fitting routines are named here, so adding one without listing it is the
    way this check can be defeated; the campaign runner's tripwire covers that.
    """
    src = module_path.read_text()
    tree = ast.parse(src)
    fitting = {"FactorModel", "fit", "fit_surface_backward", "PCA", "varimax"}
    leaks, allowed = [], []
    for node in ast.walk(tree):
        if not isinstance(node, ast.Call):
            continue
        name = getattr(node.func, "attr", None) or getattr(node.func, "id", None)
        if name not in fitting:
            continue
        args = [a for a in node.args if isinstance(a, ast.Name)]
        for a in args:
            (leaks if a.id in {"v_df", "valid", "fs_v"} else allowed).append(
                f"{name}({a.id}) at line {node.lineno}")
    return {"fitting_calls_on_design": sorted(set(allowed)),
            "fitting_calls_on_validation": sorted(set(leaks)),
            "leak_free": not leaks}


def main() -> int:
    design = load_design()
    ext = pilot.external_points(10**6, seed=1, kind="complement")
    Cd, Ce = coded(design), coded(ext)
    d_corner = (np.abs(np.abs(Cd) - 1) < 1e-9).all(axis=1)
    e_corner = (np.abs(np.abs(Ce) - 1) < 1e-9).all(axis=1)
    R: dict = {"design_runs": int(len(design)), "external_runs": int(len(ext))}
    fail: list[str] = []

    def check(num, name, ok, detail):
        R[f"check_{num}_{name}"] = {"pass": bool(ok), **detail}
        if not ok:
            fail.append(f"{num}. {name}")
        print(f"  [{'PASS' if ok else 'FAIL'}] {num}. {name}")
        for k, v in detail.items():
            print(f"          {k}: {v}")

    print("external validation design verification\n")

    # 1. disjointness
    shared = {tuple(r) for r in np.round(Ce, 6)} & {tuple(r) for r in np.round(Cd, 6)}
    check(1, "no external run appears in the fitting design",
          len(shared) == 0, {"shared_runs": len(shared)})

    # 2. opposite defining relation
    dr_d, dr_e = defining_relation(Cd[d_corner]), defining_relation(Ce[e_corner])
    check(2, "fitting and validation fractions have opposite defining relation",
          dr_d == {1.0} and dr_e == {-1.0},
          {"design_sign_product": sorted(dr_d), "external_sign_product": sorted(dr_e)})

    # 3. same resolution
    res_d, res_e = resolution(Cd[d_corner]), resolution(Ce[e_corner])
    check(3, "complementary fraction has the same factorial resolution",
          res_d == res_e, {"design_resolution": res_d, "external_resolution": res_e})

    # 4. feasibility
    bad = []
    for p in PARAMS:
        lo, hi = BOUNDS[p]
        v = ext[p].to_numpy(dtype=float)
        if v.min() < lo - 1e-9 or v.max() > hi + 1e-9:
            bad.append(f"{p} outside [{lo}, {hi}]")
        if p in INTS and not np.allclose(np.round(v), v, atol=1e-9):
            # integers are realized by rounding; record the largest displacement
            R.setdefault("integer_rounding_displacement", {})[p] = float(
                np.abs(np.round(v) - v).max())
    for p in INTS:
        lo, hi = BOUNDS[p]
        rv = np.round(ext[p].to_numpy(dtype=float))
        if rv.min() < lo or rv.max() > hi:
            bad.append(f"{p} leaves its bounds after rounding")
    check(4, "every configuration is feasible under the declared bounds and types",
          not bad, {"violations": bad or "none",
                    "integer_rounding_displacement":
                        R.get("integer_rounding_displacement", {})})

    # 5. axial runs distinct from both fractions
    axial = Ce[~e_corner]
    all_corners = {tuple(r) for r in np.round(np.vstack([Cd[d_corner], Ce[e_corner]]), 6)}
    overlap = {tuple(r) for r in np.round(axial, 6)} & all_corners
    also_design_axial = {tuple(r) for r in np.round(axial, 6)} & \
                        {tuple(r) for r in np.round(Cd[~d_corner], 6)}
    check(5, "axial runs are distinct from both factorial fractions and from the design's own axial runs",
          len(overlap) == 0 and len(also_design_axial) == 0,
          {"axial_runs": int(len(axial)),
           "overlap_with_corners": len(overlap),
           "overlap_with_design_axial": len(also_design_axial),
           "axial_radius": float(np.abs(axial[axial != 0]).max())})

    # 6. identifiability of the response-surface terms on the external set
    terms = rsm_terms(len(PARAMS))
    A = basis(Ce, terms)
    rank = int(np.linalg.matrix_rank(A))
    A_corners_only = basis(Ce[e_corner], terms)
    rank_corners = int(np.linalg.matrix_rank(A_corners_only))
    check(6, "external set can identify the terms of the fitted response surface",
          rank == len(terms),
          {"terms": len(terms), "rank_with_axial": rank,
           "rank_corners_only": rank_corners,
           "note": ("corners alone cannot identify the quadratic terms, which is why "
                    "the axial runs are part of the specification")})

    # 7. no validation response reaches a fitting stage
    leak = check_no_validation_leak(HERE / "pilot_stage_a_screening.py")
    check(7, "no validation response can reach any fitting stage",
          leak["leak_free"], leak)

    OUT.mkdir(parents=True, exist_ok=True)
    R["all_pass"] = not fail
    (OUT / "external_validation_verification.json").write_text(json.dumps(R, indent=2))
    print(f"\n{'ALL CHECKS PASS' if not fail else 'FAILED: ' + ', '.join(fail)}")
    print(f"wrote {OUT/'external_validation_verification.json'}")
    return 1 if fail else 0


if __name__ == "__main__":
    sys.exit(main())
